// Code generated by schema/cmd/gen-tenant-tables. DO NOT EDIT.

package schema

// TenantTableSuffixes lists every table (without TablePrefix) that carries an org_id column and therefore participates in RLS.
var TenantTableSuffixes = []string{
	"api_key_sheets",
	"api_keys",
	"credentials",
	"invites",
	"memberships",
	"orgs",
	"projects",
	"sheet_rows",
	"sheet_snapshots",
	"sheet_write_attempts",
	"sheets",
	"spreadsheets",
	"todos",
}

// TenantTableNames returns TenantTableSuffixes prefixed with the given TablePrefix.
func TenantTableNames(prefix string) []string {
	out := make([]string, len(TenantTableSuffixes))
	for i, s := range TenantTableSuffixes {
		out[i] = prefix + s
	}
	return out
}
